export const LOGIN = 'LOGIN';
export const IS_LOGGED = 'IS_LOGGED';
export const LOGIN_HAS_ERROR = 'LOGIN_HAS_ERROR';

export const SIGNUP = 'SIGNUP';
export const IS_SIGNUP = 'IS_SIGNUP';
export const SIGNUP_HAS_ERROR = 'SIGNUP_HAS_ERROR';

export const FORGETPASS = 'FORGETPASS';
export const IS_FORGETPASS = 'IS_FORGETPASS';
export const FORGETPASS_HAS_ERROR = 'FORGETPASS_HAS_ERROR';

export const RESETPASS = 'RESETPASS';
export const IS_RESETPASS = 'IS_RESETPASS';
export const RESETPASS_HAS_ERROR = 'RESETPASS_HAS_ERROR';

export const DRAWERMENU = 'DRAWERMENU';
export const IS_DRAWERMENU = 'IS_DRAWERMENU';
export const DRAWERMENU_HAS_ERROR = 'DRAWERMENU_HAS_ERROR';

export const SIDESCREEN = 'SIDESCREEN';
export const IS_SIDESCREEN = 'IS_SIDESCREEN';
export const SIDESCREEN_HAS_ERROR = 'SIDESCREEN_HAS_ERROR';

export const CREATEEVENT = 'CREATEEVENT';
export const IS_CREATEEVENT = 'IS_CREATEEVENT';
export const CREATEEVENT_HAS_ERROR = 'CREATEEVENT_HAS_ERROR';

export const TRAINING = 'TRAINING';
export const IS_TRAINING = 'IS_TRAINING';
export const TRAINING_HAS_ERROR = 'TRAINING_HAS_ERROR';

export const QUALITYINDUCTION = 'QUALITYINDUCTION';
export const IS_QUALITYINDUCTION = 'IS_QUALITYINDUCTION';
export const QUALITYINDUCTION_HAS_ERROR = 'QUALITYINDUCTION_HAS_ERROR';

export const QUALITYTRAINING = 'QUALITYTRAINING';
export const IS_QUALITYTRAINING = 'IS_QUALITYTRAINING';
export const QUALITYTRAINING_HAS_ERROR = 'QUALITYTRAINING_HAS_ERROR';

export const UPDATEMANAGER = 'UPDATEMANAGER';
export const IS_UPDATEMANAGER = 'IS_UPDATEMANAGER';
export const UPDATEMANAGER_HAS_ERROR = 'UPDATEMANAGER_HAS_ERROR';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const IS_UPLOAD_IMAGE = 'IS_UPLOAD_IMAGE';
export const UPLOAD_IMAGE_HAS_ERROR = 'UPLOAD_IMAGE_HAS_ERROR';

export const VIEWMANAGER = 'VIEWMANAGER';
export const IS_VIEWMANAGER = 'IS_VIEWMANAGER';
export const VIEWMANAGER_HAS_ERROR = 'VIEWMANAGER_HAS_ERROR';

export const VIEWEVENT = 'VIEWEVENT';
export const IS_VIEWEVENT = 'IS_VIEWEVENT';
export const VIEWEVENT_HAS_ERROR = 'VIEWEVENT_HAS_ERROR';

export const ALLEVENTS = 'ALLEVENTS';
export const IS_ALLEVENTS = 'IS_ALLEVENTS';
export const ALLEVENTS_HAS_ERROR = 'ALLEVENTS_HAS_ERROR';

export const UPCOMINGEVENTS = 'UPCOMINGEVENTS';
export const IS_UPCOMINGEVENTS = 'IS_UPCOMINGEVENTS';
export const UPCOMINGEVENTS_HAS_ERROR = 'UPCOMINGEVENTS_HAS_ERROR';

export const PASTEVENTS = 'PASTEVENTS';
export const IS_PASTEVENTS = 'IS_PASTEVENTS';
export const PASTEVENTS_HAS_ERROR = 'PASTEVENTS_HAS_ERROR';

export const CATEGORYLIST = 'CATEGORYLIST';
export const IS_CATEGORYLIST = 'IS_CATEGORYLIST';
export const CATEGORYLIST_HAS_ERROR = 'CATEGORYLIST_HAS_ERROR';

export const SUBCATEGORYLIST = 'SUBCATEGORYLIST';
export const IS_SUBCATEGORYLIST = 'IS_SUBCATEGORYLIST';
export const SUBCATEGORYLIST_HAS_ERROR = 'SUBCATEGORYLIST_HAS_ERROR';

export const SPONSORSLIST = 'SPONSORSLIST';
export const IS_SPONSORSLIST = 'IS_SPONSORSLIST';
export const SPONSORSLIST_HAS_ERROR = 'SPONSORSLIST_HAS_ERROR';

export const DELETEPROFILE = 'DELETEPROFILE';
export const IS_DELETEPROFILE = 'IS_DELETEPROFILE';
export const DELETEPROFILE_HAS_ERROR = 'DELETEPROFILE_HAS_ERROR';

export const DELETEEVENT = 'DELETEEVENT';
export const IS_DELETEEVENT = 'IS_DELETEEVENT';
export const DELETEEVENT_HAS_ERROR = 'DELETEEVENT_HAS_ERROR';

export const UPDATEEVENT = 'UPDATEEVENT';
export const IS_UPDATEEVENT = 'IS_UPDATEEVENT';
export const UPDATEEVENT_HAS_ERROR = 'UPDATEEVENT_HAS_ERROR';